### ISSUE TITLE
es2015 modules?

### ISSUE THREAD

**Issue by heyitsmeuralex** [nathan/parcel#9] opened 2017-07-16 21:36 UTC
Parcel is great, but using it stops me from using rollup/tree shaking in my production builds because rollup requires the usage of import/export commands.

Parcel is awesome for speeding up development builds. Would it be possible for it to maintain the same speed whilst supporting es2015 module syntax?

**Comment by nathan** [comment] 2017-07-16 23:58
Sort of. The problem is that finding/parsing `import`/`export` statements is much more complicated than finding/parsing <code>require(<var>"constant string"</var>)</code>, and that `import`/`export` aren't valid syntax in runtimes that don't understand them (conversely, `require(…)` is just a function call and works fine in browsers, etc.). For example, this is a valid export statement:

```js
export var a = someFn(1, notVar = 2, someFn(3, 4, 5)), b = 2
```

Which has to be transformed into this:

```js
var a = exports.a = someFn(1, notVar = 2, someFn(3, 4, 5)), b = exports.b = 2
//                                                the hard part ^~~~~~~~~~~
```

…without parsing the initialization expression as JavaScript. And there are [a bunch more](https://tc39.github.io/ecma262/#prod-ExportDeclaration) productions to handle too.

I think it's possible to just do delimiter-balancing to get through initialization expressions, function/class bodies, etc., which is much faster than parsing the entire thing but much slower than the quick and somewhat dirty regex search (with no replacement/substitution of any kind) that parcel uses for `require(…)` imports.

I do really like the `import`/`export` syntax and the static analysis benefits that come with using it. I might look into this if I have time.

**Comment by nathan** [comment] 2017-07-27 12:58
@heyitsmeuralex I just finished the initial version of [Parcel Redux](https://github.com/nathan/parcel-redux), which fully supports ES6 module syntax and is about 5-10 times faster than the original Parcel. On [compasscode/editor](https://github.com/compasscode/editor) I get a nice speedup compared to watchify:

```sh
> watchify js/editor.js -o assets/editor.js -t [ rollupify --config rollup.config.js ] -dv
816848 bytes written to assets/editor.js (1.20 seconds) at 7:47:47 AM
816848 bytes written to assets/editor.js (0.23 seconds) at 7:47:52 AM
816848 bytes written to assets/editor.js (0.17 seconds) at 7:47:54 AM
816848 bytes written to assets/editor.js (0.18 seconds) at 7:47:55 AM
816848 bytes written to assets/editor.js (0.17 seconds) at 7:47:57 AM

> parcel -wE js/editor.js assets/editor.js
ready in 22 ms
generate assets/editor.js in 25 ms
generate assets/editor.js in 23 ms
generate assets/editor.js in 27 ms
generate assets/editor.js in 22 ms
```

(Parcel generates source maps in a separate file by default, but if you need them inline just pass `-I`.)

**Comment by nathan** [comment] 2017-07-27 13:02
Fixed in [Parcel Redux](https://github.com/nathan/parcel-redux).

**Closed by nathan** 2017-07-27 13:02 UTC
